### ISSUE TITLE
Replace with list comprehension

### ISSUE THREAD

**Issue by gregwhorley** [yogeshkk/K8sPurger#18]
https://github.com/yogeshkk/K8sPurger/blob/f91e1d7d8da2f56078529e756223ee4738a5fe51/K8sPurger.py#L77-L82

Could be:

```
def Diffrance(listA, listB):
    return [i for i in listA if i not in listB]
```

**Comment by yogeshkk** [comment]
@gregwhorley look like it can work but I don't have access to my PC for atleast a week. Can you test and raise MR. Will happy to merge.

**Comment by gregwhorley** [comment]
https://github.com/yogeshkk/K8sPurger/pull/19

**Comment by yogeshkk** [comment]
Thanks for contribution. MR is merged so closing the issue
